services:
  - type: web
    name: harassment-detection-app
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: streamlit run app.py --server.port=$PORT --server.address=0.0.0.0
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"

  - type: web
    name: harassment-detection-flask
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn --workers 1 --threads 4 --worker-class gthread --bind 0.0.0.0:$PORT stream_server:app
    autoDeploy: true
    envVars:
      - key: PYTHONUNBUFFERED
        value: "1"
